### ISSUE TITLE
FUNZIONALITÀ: scegliere la qualità video

### ISSUE THREAD

**Issue by Arutosio** [NextLight/Divvvv#5]
Si potrebbe aggiungere la qualità se disponibile su vvvid del video da scaricare?

**Comment by NextLight** [comment]
In teoria scarica già la versione con la qualità maggiore. Già fa schifo quella, non sono interessato a dare la possibilità di scaricare quella ancora peggiore.
Se questo funziona male e scarica la versione SD invece che quella in "HD" allora riapri pure l'issue con un esempio di dove fallisce.
