### ISSUE TITLE
Lista contenuti sparita/impossibile scaricare

### ISSUE THREAD

**Issue by Razorbacktrack** [NextLight/Divvvv#7]
Da qualche giorno il programma non visualizza piu' la lista degli anime e di conseguenza non è possibile effettuare il download di qualsiasi contenuto.

**Comment by Baphometto** [comment]
Confermo il bug e aggiungerei che alla fine Eren muore

**Comment by NextLight** [comment]
Grazie per la segnalazione. Sinceramente sono stupito che sto schifo di codice abbia funzionato per 5 anni.
Dovrei aver fixato il problema e per la prima volta ho pure [pubblicato la versione già compilata](https://github.com/NextLight/Divvvv/releases).
